language: node_js
node_js:
    - '8'
    - '9'
    - '10'
script:
    - yarn format
    - yarn check:src
    - yarn build
branches:
    only:
        - master
cache:
    directories:
        - $HOME/.npm
