apiVersion: v1
kind: Service
metadata:
  name: photomosaic-fe
spec:
  selector:
    app: photomosaic-fe
  ports:
    - port: 8080
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photomosaic-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photomosaic-fe
  template:
    metadata:
      labels:
        app: photomosaic-fe
    spec:
      containers:
        - name: photomosaic-fe
          image: quay.io/vbartoli/photomosaic-app
          ports:
            - containerPort: 4000
          env:
            - name: IMAGE_PATH
              value: http://photomosaic-be:5030
          imagePullPolicy: Always
